name: Terraform Apply PROD

on:
  workflow_dispatch:    # ← только вручную через кнопку на GitHub!
    inputs:
      confirm:
        description: 'Введи DEPLOY чтобы подтвердить деплой в prod'
        required: true

env:
  TF_VERSION: "1.14.8"
  WORKING_DIR: "./environments/prod"

jobs:
  terraform-apply-prod:
    name: Terraform Apply PROD
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'DEPLOY' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TF_VAR_your_ip: ${{ secrets.YOUR_IP }}
        run: terraform apply -auto-approve -no-color